name: Deploy Storybook Action
on
  push:
    paths: 
      - '**.stories.jsx'
      - 'packages/**/stories'
      - '/stories/**'
  pull_request:
  workflow_dispatch:
jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
        run: yarn install
      - name: Run build storybook
        run: yarn build-storybook
      - name: Run deploy storybook
        run: |
          git config --global user.email ${{vars.EMAIL}}
          git config --global user.name ${{vars.NAME}}
          git remote set-url origin https://${{vars.NAME}}:${{secrets.GITHUB_TOKEN}}@github.com/DesignSystemLab/design-system.git
          yarn gh-pages -d storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
