name: Jest Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     path: main
      # - name: Set Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install # will run `yarn install` command
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }} # if needed
      # - name: Test the app
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test # will run `yarn test` command
