name: Release Action
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          token: ${{ secrets.WORKFLOW_TOKEN }}
          fetch-depth: '0'
      - name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
        run: yarn install
      - name: Build packages
        run: yarn build
      - name: Add GiHub Package Token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.JDS_RELLEASE_TOKEN }}" > ~/.npmrc
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
