on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Increase memory limit
        run: export NODE_OPTIONS="--max_old_space_size=4096"
      - name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
        run: yarn install
      - name: Run tests
        run: yarn test
